# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    - always_declare_return_types # Siempre especifica el tipo de retorno.
    - avoid_print # No uses print() en código de producción.
    - camel_case_types # Nombres de clases en CamelCase.
    - constant_identifier_names # Nombres de constantes en snake_case.
    - deprecated_member_use_from_same_package # Evita usar miembros deprecados de la misma librería.
    - file_names # Nombres de archivos en snake_case.
    - prefer_const_constructors # Usa constructores constantes donde sea posible.
    - prefer_final_locals # Usa final para variables locales que no cambian.
    - prefer_final_parameters # Usa final para los parámetros de la función.
    - prefer_single_quotes # Usa comillas simples en lugar de dobles.
    - slash_for_doc_comments # Usa /// para la documentación.