// Mocks generated by Mockito 5.4.6 from annotations
// in seguimiento_norandino/test/domain/use_cases/aprobar_denegar_ruta_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:seguimiento_norandino/core/errors/failures.dart' as _i5;
import 'package:seguimiento_norandino/features/rutas/domain/entities/ruta.dart'
    as _i6;
import 'package:seguimiento_norandino/features/rutas/domain/repositories/rutas_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RutasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRutasRepository extends _i1.Mock implements _i3.RutasRepository {
  MockRutasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ruta>>> getRutas({
    String? zona,
    String? agencia,
    String? asesorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRutas, [], {
              #zona: zona,
              #agencia: agencia,
              #asesorId: asesorId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ruta>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Ruta>>(
                    this,
                    Invocation.method(#getRutas, [], {
                      #zona: zona,
                      #agencia: agencia,
                      #asesorId: asesorId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Ruta>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>> getRutaById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRutaById, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>.value(
              _FakeEither_0<_i5.Failure, _i6.Ruta>(
                this,
                Invocation.method(#getRutaById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>> createRuta(_i6.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#createRuta, [ruta]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>.value(
              _FakeEither_0<_i5.Failure, _i6.Ruta>(
                this,
                Invocation.method(#createRuta, [ruta]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>> updateRuta(_i6.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#updateRuta, [ruta]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>.value(
              _FakeEither_0<_i5.Failure, _i6.Ruta>(
                this,
                Invocation.method(#updateRuta, [ruta]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteRuta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRuta, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteRuta, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>> assignAsesor(
    String? rutaId,
    String? asesorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignAsesor, [rutaId, asesorId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>.value(
              _FakeEither_0<_i5.Failure, _i6.Ruta>(
                this,
                Invocation.method(#assignAsesor, [rutaId, asesorId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Ruta>>);
}
