// Mocks generated by Mockito 5.0.0 from annotations
// in complete_seguimiento_use_case_test.dart.
import 'package:mockito/mockito.dart';
import '../../../lib/features/seguimientos/domain/repositories/seguimientos_repository.dart';

class MockSeguimientosRepository extends Mock implements SeguimientosRepository {}
